Script started on 2024-06-16 00:04:30+06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="104" LINES="49"]
[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ cd
[?2004l[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ script show[K[K[K[K[K[K[K[K[K[K[Kwho [Kami
[?2004lniloy
[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ echo $SHELL
[?2004l/bin/bash
[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ pa[Kwd
[?2004l/home/niloy
[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ who[K[K[Kunma[K[Kame -a
[?2004lLinux LAPTOP-UB23RQRP 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ gcc --version -std=c17 [K
[?2004lgcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[?2004h]0;niloy@LAPTOP-UB23RQRP: ~[01;32mniloy@LAPTOP-UB23RQRP[00m:[01;34m~[00m$ exit
[?2004lexit

Script done on 2024-06-16 00:05:35+06:00 [COMMAND_EXIT_CODE="0"]
